# Generated by Django 4.2.1 on 2023-05-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interships', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intern',
            name='avatar',
            field=models.ImageField(default='avatars/default.jpg', upload_to='avatars/'),
        ),
    ]
