# Generated by Django 4.2.1 on 2023-05-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interships', '0002_alter_intern_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolestatus',
            name='status',
            field=models.CharField(choices=[('0', 'Rejected'), ('1', 'Under analysis'), ('2', 'Approved')], default='1', max_length=1),
        ),
    ]
