# Generated by Django 4.2.1 on 2023-05-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interships', '0003_alter_rolestatus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intern',
            name='number',
            field=models.CharField(max_length=15),
        ),
    ]
